#!/bin/bash

for version in 1.8.7-p371 1.9.3-p392 2.0.0-p0 jruby-1.7.3; do
  cmd="rake appraisal:install"
  echo -e "\033[1;33m[$version] $cmd\033[0m"
  export RBENV_VERSION=$version
  eval $cmd || exit $?
  echo
done
