#!/bin/bash

for version in $(<script/TARGETED_VERSIONS); do
  cmd="rake appraisal:install"
  echo -e "\033[1;33m[$version] $cmd\033[0m"
  export RBENV_VERSION=$version
  eval $cmd || exit $?
  echo
done
