#!/bin/bash

exitstatus=0
for version in 1.8.7-p371 1.9.3-p392 2.0.0-p0; do
  cmd="bundle install --quiet && bundle exec rake"
  echo
  echo -e "\033[1;33m[$version] $cmd\033[0m"
  echo
  export RBENV_VERSION=$version
  eval $cmd
  if [ $? -ne 0 ]; then exitstatus=1; fi
done

if [ $exitstatus -eq 0 ]; then
  echo -e "\033[1;33mTest suite passed!\033[0m"
else
  echo -e "\033[1;33mTest suite failed!\033[0m"
fi
echo
