name: GitHub Pages

on:
  push:
    tags:
      - "*"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Update version
        run: |
          rake gh-pages:version:update
      - name: Deploy
        run: |
          cd gh-pages
          if [ "$(git status --porcelain)" != "" ]; then
            git add --all
            git config user.name github-actions
            git config user.email github-actions@github.com
            tag=$(echo ${GITHUB_REF} | sed -e 's,^refs/tags/,,')
            git commit -m "Release ${tag}!!!"
            git push
          fi
